# Generated by Django 4.1.1 on 2023-05-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorprofile",
            name="twitter_handle",
            field=models.CharField(default="@brandishseo", max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="snippet",
            field=models.CharField(
                help_text="Excerpt used in article list preview card.",
                max_length=200,
            ),
        ),
    ]
