# Generated by Django 4.1.1 on 2023-05-02 19:19

import django.core.validators
from django.db import migrations, models

import blog.validators


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_authorprofile_twitter_handle_alter_blogpage_snippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorprofile",
            name="twitter_handle",
            field=models.CharField(
                max_length=16,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    blog.validators.validate_twitter_handle,
                ],
            ),
        ),
    ]
