# Generated by Django 4.1.1 on 2023-04-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("project_name", models.CharField(max_length=20)),
                ("order_completed", models.BooleanField(default=False)),
                ("website", models.CharField(max_length=200)),
                ("additional_info", models.TextField(blank=True)),
                ("keywords", models.CharField(blank=True, max_length=200)),
                ("competitor", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["-order_completed"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=7
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[("SEO", "SEO"), ("Keyword", "Keyword")],
                        max_length=7,
                    ),
                ),
            ],
        ),
    ]
