# Generated by Django 4.1.1 on 2025-02-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0003_alter_service_options_service_featured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="package_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Keyword Strategy"),
                    (2, "SEO Strategy"),
                    (3, "Link Building Strategy"),
                ],
                unique=True,
            ),
        ),
    ]
