# Generated by Django 4.1.1 on 2025-06-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0004_alter_service_package_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="price_id",
            field=models.CharField(
                default="price_1K6njzEF5U15SUxG3lEhbezO",
                help_text="The Stripe price id",
                max_length=35,
            ),
            preserve_default=False,
        ),
    ]
