# Generated by Django 4.1.1 on 2025-06-19 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0003_project_strategy_xlsx_alter_project_strategy_doc_and_more",
        ),
        ("checkout", "0005_service_price_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-order_processed_date"]},
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_completed",
            new_name="order_processed",
        ),
        migrations.AddField(
            model_name="order",
            name="order_abandoned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="order_processed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="projects.project",
            ),
        ),
    ]
