# Generated by Django 4.1.1 on 2022-10-05 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Author profiles'},
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='featured_article',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='snippet',
            field=models.CharField(default='Post snippet', help_text='Excerpt used in article list preview card.', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(help_text='Brief page description used in the intro section.'),
        ),
        migrations.AlterField(
            model_name='categoryindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(help_text='Brief page description used in the intro section.'),
        ),
    ]
